import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const forsDemiBold = localFont({
  src: [
    {
      path: "./fonts/TT-Fors-Trial-DemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-demibold",
  display: "swap",
});
const forsRegular = localFont({
  src: [
    {
      path: "./fonts/TT-Fors-Trial-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-regular",
  display: "swap",
});
const forsMedium = localFont({
  src: [
    {
      path: "./fonts/TT-Fors-Trial-Medium.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-medium",
  display: "swap",
});
const forsDemiBoldItalic = localFont({
  src: [
    {
      path: "./fonts/TT-Fors-Trial-DemiBold-Italic.ttf",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-demibold-italic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vora event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${forsDemiBold.variable} ${forsRegular.variable} ${forsMedium.variable} ${forsDemiBoldItalic.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
